### ISSUE TITLE
$name on FeatureLayer

### ISSUE THREAD

**Issue by SimonSoftware** [2amigos/yii2-leaflet-extension#11]
Cannot add $name in LayerGroup (and on FeatoreGroup).
And in encode() function 
```php
 if (!empty($name)) {
            $js = "var $name = $js" . ($map !== null ? "" : ";");
}
```
is missed.

**Comment by tonydspaniard** [comment]
Will review when I have some free time... Thanks

**Comment by SimonSoftware** [comment]
OK, can i fork and modify?
I do not know very well how to use github but I can try.

Paolo

Il 22/02/2015 13:28, Antonio Ramirez ha scritto:

**Comment by tonydspaniard** [comment]
sure, thats what github is all about :+1:

**Comment by tonydspaniard** [comment]
@SimonSoftware This repository is now not a subtree split. If you are to propose a PR, do it on this repo.

**Comment by tonydspaniard** [comment]
This has been updated. Once all tests are done will update the version: https://github.com/2amigos/yii2-leaflet-extension/blob/master/src/layers/LayerGroup.php#L106
