### ISSUE TITLE
LatLng Values routinely get encoded as strings

### ISSUE THREAD

**Issue by Okeanos** [2amigos/yii2-leaflet-extension#16]
I recently extended my existing map with polylines using the supplied wrapper class `dosamigos\leaflet\layers\PolyLine`.
However, even when creating a perfectly fine Polyline:
```php
$path = new PolyLine();
$path->setLatLngs([
  new LatLng(['lat' => …, 'lng' => …]),
  new LatLng(['lat' => …, 'lng' => …])
]);
```
The resulting JS fails. This is because the current implementation of the encode function does not pass `JSON_NUMERIC_CHECK ` onto the `yii\helpers\Json::encode()` method used to transform the `LatLng` object into JSON which results in string values instead of keeping the float values. 
This is also missing for Markers, however, in this case Leaflet itself appears to be more forgiving.
Interestingly, for the map object itself the float values are kept as floats instead of being converted to strings even though the same process is used … maybe I am overlooking something?

**Comment by tonydspaniard** [comment]
Will review it asap.

**Comment by Okeanos** [comment]
Any progress on this issue?

**Comment by tonydspaniard** [comment]
@Okeanos I had a lot of issues with having free time to support the extensions. Do you mind providing me sample code to duplicate the issue? Thanks in advance.

**Comment by Okeanos** [comment]
No worries. I'll see whether I can whip something up before the holidays.

**Comment by tonydspaniard** [comment]
It doesn't need to be too large, just replicating the issue. I have time now to support our extensions.

**Comment by tonydspaniard** [comment]
@Okeanos I pushed a fix, let me know if it works. Thanks.

**Comment by Okeanos** [comment]
This fix appears to be working. I don't have any test cases for the following wrapper classes, though, so I can't say whether the respective `encode()` function also needs this treatment: `FeatureGroup`, `LayerGroup`, `GeoJson`, `Polygon`

Thank you for taking care of it :)

**Comment by tonydspaniard** [comment]
@Okeanos Good news.  I'll update revision tag then. I have plans to update the library to make it much better in structure.
