### ISSUE TITLE
Using more than one plug in at a time

### ISSUE THREAD

**Issue by davidjeddy** [2amigos/yii2-leaflet-extension#17]
After setting up the map (working) my project requires the usage of both the geoSearch and another plugin. However, this does not seem to be implemented at the moment.
Exp:
```
    $leaflet
        ->addlayerGroup($markerLayerGroup) // add layerGroup (of markers)
        ->addLayer( new \dosamigos\leaflet\layers\TileLayer([
            'clientOptions' => [
                'attribution' => \Yii::$app->keyStorage->get('common.teburu4.tileAttribution')
            ],
            'urlTemplate'   => \Yii::$app->keyStorage->get('common.teburu4.tileProviderUrl'),
        ]))
        ->installPlugin($geoSearchPlugin)
        ->installPlugin($drawPlugin);
```

This results in a ' PHP Fatal Error – yii\base\ErrorException
Call to a member function installPlugin() on a non-object' error. So I broke the `installPlugin()` method call  out.
```
    $leaflet
        ->addlayerGroup($markerLayerGroup) // add layerGroup (of markers)
        ->addLayer( new \dosamigos\leaflet\layers\TileLayer([
            'clientOptions' => [
                'attribution' => \Yii::$app->keyStorage->get('common.teburu4.tileAttribution')
            ],
            'urlTemplate'   => \Yii::$app->keyStorage->get('common.teburu4.tileProviderUrl'),
        ]));
    $leaflet->installPlugin($geoSearchPlugin)
    $leaflet->installPlugin($drawPlugin);
```
Only the LAST plugin is displayed in the map element.

How can the Leaflet extension be extended to handle more than one plugin?

**Comment by tonydspaniard** [comment]
@davidjeddy it does handle more than one plugin, the problem with your code is the concatenation of methods on the first example. See here: https://github.com/2amigos/yii2-leaflet-extension/blob/master/src/LeafLet.php#L238. 

The second should work. Maybe there is a plugin conflict issue?
