### ISSUE TITLE
Using Mapbox's Leaflet.js version instead of Leaflet's

### ISSUE THREAD

**Issue by devleaks** [2amigos/yii2-leaflet-extension#32]
This is not an issue but rather a question or enhancemet request.
How difficult would it be to use Mapbox's Leaflet.js' version instead of Leaflet's?
Is it conceivable to offer a selector switch to select either library?
Many thanks.
P.

**Comment by tonydspaniard** [comment]
@devleaks The only thing I was using from mapbox is their tiles when they were free for developers. Their library has a slight modification of everything as far as I remember. I would have to identify the differences. But MapBox is not free, so... I am not sure is worth the effort.

**Comment by tonydspaniard** [comment]
@devleaks i have used leaflet's library with mapbox for its tiles. You can see the result here: https://codermap.io/discover

**Comment by devleaks** [comment]
Thanks.
