### ISSUE TITLE
Leaflet 1.0x series

### ISSUE THREAD

**Issue by arjenmeijer** [2amigos/yii2-leaflet-extension#35]
Is upgrading to the 1.0x versions in your planning?

**Comment by tonydspaniard** [comment]
Yes @arjenmeijer didn't updated yet. I will asap. Any PR are also welcome.

**Comment by tonydspaniard** [comment]
@arjenmeijer is done https://github.com/2amigos/yii2-leaflet-extension/blob/master/composer.json#L30

**Comment by arjenmeijer** [comment]
Thanks
