### ISSUE TITLE
Please release version with bounds client option

### ISSUE THREAD

**Issue by squio** [2amigos/yii2-leaflet-extension#37]
Just noticed that the option to set map bounds is not yet released.
Could you please release this version?

    $leaflet->clientOptions['bounds'] = $myPolyLine->bounds->encode();

I desperately want to be able to do this!

**Comment by squio** [comment]
Quick work around for now, in `composer.json`:

    "require": {
        "2amigos/yii2-leaflet-extension": "dev-master",
        ...
    },
    "repositories": [
        {
            "type": "git",
            "url": "https://github.com/2amigos/yii2-leaflet-extension.git"
        }
    ]

Followed by your regular `composer update` on the command line.

**Comment by tonydspaniard** [comment]
done @squio Thanks!
