### ISSUE TITLE
Maps do not work

### ISSUE THREAD

**Issue by vov4ik08** [2amigos/yii2-leaflet-extension#39]
Hi. I try to use example from this reposytory and i see only grey backgroud.
![123](https://cloud.githubusercontent.com/assets/2761022/25390829/4d390444-29dd-11e7-81d5-0377d5931593.jpg)
If i try use othere library (google maps) Effect same. What am I doing wrong? No error on browser console. Please help me. Thank you

**Comment by tonydspaniard** [comment]
Your problem is the tile provider. You have to change it. Try stamen: http://maps.stamen.com/#toner/12/37.7706/-122.3782
