### ISSUE TITLE
Map as global variable

### ISSUE THREAD

**Issue by fabioaccetta** [2amigos/yii2-leaflet-extension#5]
Looking inside generated js code, I see that the "map" variable is local, inside a map_init() function, so I can't use it outside its scope.

Is there a plan to make this variable global, so can be used page-wide? Or must the developer implement something like this?

Inside a view:

``` php
$this->registerJS('var globalMap;', View::POS_HEAD); // global variable

$tileConfig = [
    '...' => '...',
    'map' => 'localMap', // local variable
];
$tileLayer = new TileLayer($tileConfig);

$leafConfig = [
    '...' => '...',
    'tileLayer' => $tileLayer,
];
$leafLet = new LeafLet($leafConfig);
$leafLet->appendJS('globalMap = localMap;'); // use globalMap page-wide
```

Thanks.
Regards.

**Comment by GFargo** [comment]
:+1: great post, very helpful.

**Comment by nigelterry** [comment]
As a variant, use appendJs() to insert whatever js you need within the scope that includes map.

For example to insert a block of js from a file, try:
$leaflet->appendJs(file_get_contents('js/maptools.js'));

This saves making a global which is rarely a good idea.
