### ISSUE TITLE
Example not working

### ISSUE THREAD

**Issue by speixoto** [2amigos/yii2-leaflet-extension#8]
The example posted on https://github.com/2amigos/yii2-leaflet-extension dont work.

I sugest you change line 24 of dosamigos\leaflet\layers\Layer to public $map = 'map';

This way it will work out of the box since dosamigos\leaflet\widgets\Map $name var is also defaulted to 'map'.

If you dont want to make this change, you need to at least change your example to a working one, adding 'map' => 'map' to the when creating the tileLayer.

**Comment by tonydspaniard** [comment]
@speixoto you are right. Will update asap.

**Comment by tonydspaniard** [comment]
@speixoto the new version update should've fixed this
